version: '3.1'

services:
  db:
    image: postgres:14.2
    privileged: true
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: django_rest
  backend:
    build:
      context: .
    ports:
      - '8080:8080'
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate 
      && python manage.py fill_db 
      && python manage.py runserver 0.0.0.0:8080 
      "
    depends_on:
      - db