# Generated by Django 4.0.3 on 2022-03-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todolist_app.project'),
        ),
    ]
