# Generated by Django 4.0.2 on 2022-03-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
        ('todolist_app', '0002_alter_todo_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to='users_app.User', verbose_name='Пользователи'),
        ),
    ]
