version: '3.1'

services:
  db:
    image: postgres:14.2
    privileged: true
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: django_rest_db
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - '8080:8080'
    depends_on:
        - db